package com.wmd.mvp.edwardmvp.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wmd.mvp.edwardmvp.bean.PersonBean;

import com.wmd.mvp.edwardmvp.sql.PersonBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personBeanDaoConfig;

    private final PersonBeanDao personBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personBeanDaoConfig = daoConfigMap.get(PersonBeanDao.class).clone();
        personBeanDaoConfig.initIdentityScope(type);

        personBeanDao = new PersonBeanDao(personBeanDaoConfig, this);

        registerDao(PersonBean.class, personBeanDao);
    }
    
    public void clear() {
        personBeanDaoConfig.clearIdentityScope();
    }

    public PersonBeanDao getPersonBeanDao() {
        return personBeanDao;
    }

}
